import type { Driver } from './openf1';

export const mockDrivers2026: Driver[] = [
    // Red Bull Racing
    {
        driver_number: 1,
        broadcast_name: 'M. VERSTAPPEN',
        full_name: 'Max Verstappen',
        first_name: 'Max',
        last_name: 'Verstappen',
        name_acronym: 'VER',
        team_name: 'Red Bull Racing',
        team_colour: '3671C6',
        country_code: 'NED',
        headshot_url: '',
        session_key: 0,
        meeting_key: 0
    },
    {
        driver_number: 30,
        broadcast_name: 'L. LAWSON',
        full_name: 'Liam Lawson',
        first_name: 'Liam',
        last_name: 'Lawson',
        name_acronym: 'LAW',
        team_name: 'Red Bull Racing',
        team_colour: '3671C6',
        country_code: 'NZL',
        headshot_url: '',
        session_key: 0,
        meeting_key: 0
    },
    // Ferrari
    {
        driver_number: 16,
        broadcast_name: 'C. LECLERC',
        full_name: 'Charles Leclerc',
        first_name: 'Charles',
        last_name: 'Leclerc',
        name_acronym: 'LEC',
        team_name: 'Ferrari',
        team_colour: 'F91536',
        country_code: 'MON',
        headshot_url: '',
        session_key: 0,
        meeting_key: 0
    },
    {
        driver_number: 44,
        broadcast_name: 'L. HAMILTON',
        full_name: 'Lewis Hamilton',
        first_name: 'Lewis',
        last_name: 'Hamilton',
        name_acronym: 'HAM',
        team_name: 'Ferrari',
        team_colour: 'F91536',
        country_code: 'GBR',
        headshot_url: '',
        session_key: 0,
        meeting_key: 0
    },
    // Mercedes
    {
        driver_number: 63,
        broadcast_name: 'G. RUSSELL',
        full_name: 'George Russell',
        first_name: 'George',
        last_name: 'Russell',
        name_acronym: 'RUS',
        team_name: 'Mercedes',
        team_colour: '6CD3BF',
        country_code: 'GBR',
        headshot_url: '',
        session_key: 0,
        meeting_key: 0
    },
    {
        driver_number: 12,
        broadcast_name: 'K. ANTONELLI',
        full_name: 'Kimi Antonelli',
        first_name: 'Kimi',
        last_name: 'Antonelli',
        name_acronym: 'ANT',
        team_name: 'Mercedes',
        team_colour: '6CD3BF',
        country_code: 'ITA',
        headshot_url: '',
        session_key: 0,
        meeting_key: 0
    },
    // McLaren
    {
        driver_number: 4,
        broadcast_name: 'L. NORRIS',
        full_name: 'Lando Norris',
        first_name: 'Lando',
        last_name: 'Norris',
        name_acronym: 'NOR',
        team_name: 'McLaren',
        team_colour: 'F58020',
        country_code: 'GBR',
        headshot_url: '',
        session_key: 0,
        meeting_key: 0
    },
    {
        driver_number: 81,
        broadcast_name: 'O. PIASTRI',
        full_name: 'Oscar Piastri',
        first_name: 'Oscar',
        last_name: 'Piastri',
        name_acronym: 'PIA',
        team_name: 'McLaren',
        team_colour: 'F58020',
        country_code: 'AUS',
        headshot_url: '',
        session_key: 0,
        meeting_key: 0
    },
    // Aston Martin
    {
        driver_number: 14,
        broadcast_name: 'F. ALONSO',
        full_name: 'Fernando Alonso',
        first_name: 'Fernando',
        last_name: 'Alonso',
        name_acronym: 'ALO',
        team_name: 'Aston Martin',
        team_colour: '358C75',
        country_code: 'ESP',
        headshot_url: '',
        session_key: 0,
        meeting_key: 0
    },
    {
        driver_number: 18,
        broadcast_name: 'L. STROLL',
        full_name: 'Lance Stroll',
        first_name: 'Lance',
        last_name: 'Stroll',
        name_acronym: 'STR',
        team_name: 'Aston Martin',
        team_colour: '358C75',
        country_code: 'CAN',
        headshot_url: '',
        session_key: 0,
        meeting_key: 0
    },
    // Alpine
    {
        driver_number: 10,
        broadcast_name: 'P. GASLY',
        full_name: 'Pierre Gasly',
        first_name: 'Pierre',
        last_name: 'Gasly',
        name_acronym: 'GAS',
        team_name: 'Alpine',
        team_colour: '2293D1',
        country_code: 'FRA',
        headshot_url: '',
        session_key: 0,
        meeting_key: 0
    },
    {
        driver_number: 7,
        broadcast_name: 'J. DOOHAN',
        full_name: 'Jack Doohan',
        first_name: 'Jack',
        last_name: 'Doohan',
        name_acronym: 'DOO',
        team_name: 'Alpine',
        team_colour: '2293D1',
        country_code: 'AUS',
        headshot_url: '',
        session_key: 0,
        meeting_key: 0
    },
    // Williams
    {
        driver_number: 23,
        broadcast_name: 'A. ALBON',
        full_name: 'Alexander Albon',
        first_name: 'Alexander',
        last_name: 'Albon',
        name_acronym: 'ALB',
        team_name: 'Williams',
        team_colour: '37BEDD',
        country_code: 'THA',
        headshot_url: '',
        session_key: 0,
        meeting_key: 0
    },
    {
        driver_number: 55,
        broadcast_name: 'C. SAINZ',
        full_name: 'Carlos Sainz',
        first_name: 'Carlos',
        last_name: 'Sainz',
        name_acronym: 'SAI',
        team_name: 'Williams',
        team_colour: '37BEDD',
        country_code: 'ESP',
        headshot_url: '',
        session_key: 0,
        meeting_key: 0
    },
    // RB
    {
        driver_number: 22,
        broadcast_name: 'Y. TSUNODA',
        full_name: 'Yuki Tsunoda',
        first_name: 'Yuki',
        last_name: 'Tsunoda',
        name_acronym: 'TSU',
        team_name: 'RB',
        team_colour: '6692FF',
        country_code: 'JPN',
        headshot_url: '',
        session_key: 0,
        meeting_key: 0
    },
    {
        driver_number: 6,
        broadcast_name: 'I. HADJAR',
        full_name: 'Isack Hadjar',
        first_name: 'Isack',
        last_name: 'Hadjar',
        name_acronym: 'HAD',
        team_name: 'RB',
        team_colour: '6692FF',
        country_code: 'FRA',
        headshot_url: '',
        session_key: 0,
        meeting_key: 0
    },
    // Sauber / Audi
    {
        driver_number: 27,
        broadcast_name: 'N. HULKENBERG',
        full_name: 'Nico Hulkenberg',
        first_name: 'Nico',
        last_name: 'Hulkenberg',
        name_acronym: 'HUL',
        team_name: 'Kick Sauber',
        team_colour: '52E252',
        country_code: 'GER',
        headshot_url: '',
        session_key: 0,
        meeting_key: 0
    },
    {
        driver_number: 87,
        broadcast_name: 'G. BORTOLETO',
        full_name: 'Gabriel Bortoleto',
        first_name: 'Gabriel',
        last_name: 'Bortoleto',
        name_acronym: 'BOR',
        team_name: 'Kick Sauber',
        team_colour: '52E252',
        country_code: 'BRA',
        headshot_url: '',
        session_key: 0,
        meeting_key: 0
    },
    // Haas
    {
        driver_number: 31,
        broadcast_name: 'E. OCON',
        full_name: 'Esteban Ocon',
        first_name: 'Esteban',
        last_name: 'Ocon',
        name_acronym: 'OCO',
        team_name: 'Haas F1 Team',
        team_colour: 'B6BABD',
        country_code: 'FRA',
        headshot_url: '',
        session_key: 0,
        meeting_key: 0
    },
    {
        driver_number: 87,
        broadcast_name: 'O. BEARMAN',
        full_name: 'Oliver Bearman',
        first_name: 'Oliver',
        last_name: 'Bearman',
        name_acronym: 'BEA',
        team_name: 'Haas F1 Team',
        team_colour: 'B6BABD',
        country_code: 'GBR',
        headshot_url: '',
        session_key: 0,
        meeting_key: 0
    },
    // Andretti Cadillac (New Team!)
    {
        driver_number: 26,
        broadcast_name: 'C. HERTA',
        full_name: 'Colton Herta',
        first_name: 'Colton',
        last_name: 'Herta',
        name_acronym: 'HER',
        team_name: 'Andretti Cadillac',
        team_colour: 'D12A38',
        country_code: 'USA',
        headshot_url: '',
        session_key: 0,
        meeting_key: 0
    },
    {
        driver_number: 98,
        broadcast_name: 'M. ANDRETTI',
        full_name: 'Marco Andretti',
        first_name: 'Marco',
        last_name: 'Andretti',
        name_acronym: 'AND',
        team_name: 'Andretti Cadillac',
        team_colour: 'D12A38',
        country_code: 'USA',
        headshot_url: '',
        session_key: 0,
        meeting_key: 0
    }
];
